describe('template spec', () => {
  it('passes', () => {
   

cy.visit('http://localhost:3000/');
cy.get('.css-1e6y48t-MuiButtonBase-root-MuiButton-root:nth-child(1)').click();
cy.get('#email').type('zewdu@gmail.com');
cy.get('#password').type('1234');
cy.get('#email').click();
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#email').type('{backspace}');
cy.get('#password').click();
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('#password').type('{backspace}');
cy.get('.MuiTypography-body1').click();
cy.get('.PrivateSwitchBase-input').click();
cy.get('.bg-green-700').click();
cy.get('.css-164r41r').submit();
cy.get('tr:nth-child(4) > .fc-day-fri > .fc-daygrid-day-frame').click();
cy.get('#yourSelect').click();
cy.get('#yourSelect').type('Semester I End');
cy.get('#yourSelect').click();
cy.get('.hover\3A bg-green-500').click();
cy.get('form').submit();
cy.get('a:nth-child(5) > .flex').click();
cy.get('[data-testid=username]').click();
cy.get('[data-testid=username]').type('nmb');
cy.get('.w-full:nth-child(2) .focus\3A border-2').click();
cy.get('.w-full:nth-child(2) .focus\3A border-2').type('asf');
cy.get('.w-full:nth-child(4) .focus\3A border-2').click();
cy.get('.w-full:nth-child(4) .focus\3A border-2').type('fafafdsadf');
cy.get('.w-full:nth-child(3) .focus\3A border-2').click();
cy.get('.w-full:nth-child(3) .focus\3A border-2').type('adf');
cy.get('.w-full:nth-child(5) #yourSelect').click();
cy.get('.w-full:nth-child(5) #yourSelect').type('Male');
cy.get('.w-full:nth-child(5) #yourSelect').click();
cy.get('#dob').click();
cy.get('#dob').type('2024-05-14');
cy.get('.w-full:nth-child(7) #yourSelect').click();
cy.get('.w-full:nth-child(7) #yourSelect').type('2');
cy.get('.w-full:nth-child(7) #yourSelect').click();
cy.get('.w-full:nth-child(8) #yourSelect').click();
cy.get('.w-full:nth-child(8) #yourSelect').type('2');
cy.get('.w-full:nth-child(8) #yourSelect').click();
cy.get('.flex:nth-child(5) > .w-full:nth-child(1) .border-0').click();
cy.get('.flex:nth-child(5) > .w-full:nth-child(1) .border-0').type('{backspace}');
cy.get('.flex:nth-child(5) > .w-full:nth-child(1) .border-0').type('{backspace}');
cy.get('.flex:nth-child(5) > .w-full:nth-child(1) .border-0').type('{backspace}');
cy.get('.flex:nth-child(5) > .w-full:nth-child(1) .border-0').type('vbfh@gmail.com');
cy.get('.flex:nth-child(5) > .w-full:nth-child(2) .border-0').click();
cy.get('.flex:nth-child(5) > .w-full:nth-child(2) .border-0').type('09');
cy.get('.flex:nth-child(5) > .w-full:nth-child(4) .border-0').click();
cy.get('.flex:nth-child(5) > .w-full:nth-child(4) .border-0').type('720943102');
cy.get('.flex:nth-child(5) > .w-full:nth-child(5) .border-0').click();
cy.get('.flex:nth-child(5) > .w-full:nth-child(5) .border-0').type('83962124');
cy.get('.flex:nth-child(5) > .w-full:nth-child(3) .border-0').click();
cy.get('.flex:nth-child(5) > .w-full:nth-child(3) .border-0').type('38470129');
cy.get('.w-6 > path').click();
cy.get('#photo').click();
cy.get('.p-3').click();
cy.get('form').submit();
cy.get('.hover\3A cursor-pointer .MuiTypography-root').click();
cy.get('.text-white > .MuiTypography-root').click();
cy.get('#yourSelect').click();
cy.get('#yourSelect').type('2');
cy.get('#yourSelect').click();
cy.get('.mt-2').click();
cy.get('.boxshadow').submit();
cy.get('.\__className_725fdb').click();
cy.get('.Mui-selected').click();
cy.get('[data-testid=ExpandMoreTwoToneIcon]').click();
cy.get('.MuiButton-fullWidth').click();
cy.get('#email').type('zewdu@gmail.com');
cy.get('#password').type('1234');
})
})