-- AlterTable
ALTER TABLE "SubjectTotals" ADD COLUMN     "averageScore" DOUBLE PRECISION,
ALTER COLUMN "totalScore1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalScore2" SET DATA TYPE DOUBLE PRECISION;
